apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "scraperBot.fullname" . }}
  labels:
    {{- include "scraperBot.labels" . | nindent 4 }}
spec:
  {{ toYaml .Values.cronJob | nindent 2 }}
  jobTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scraperBot.selectorLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            {{- include "scraperBot.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: "Never"
          serviceAccountName: {{ include "scraperBot.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.containerSecurityContext | nindent 16 }}
              image: "{{ .Values.image.registry}}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              env:
                {{- if .Values.diskCache.enabled }}
                - name: "SB__CACHE"
                  value: diskcache:/var/cache/scraper-bot
                {{- else if .Values.redis.enabled }}
                - name: "SB__CACHE"
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "common.names.fullname" .Subcharts.redis }}-svcbind
                      key: uri
                {{- else }}
                []
                {{- end }}
              volumeMounts:
                - mountPath: /etc/scraper-bot/config.yaml
                  name: config
                  subPath: config.yaml
              {{- if .Values.diskCache.enabled }}
                - mountPath: /var/cache/scraper-bot
                  name: cache
              {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            - name: config
              secret:
                secretName: {{ include "scraperBot.fullname" . }}-config
            {{- if .Values.diskCache.enabled }}
            - name: cache
              persistentVolumeClaim:
                claimName: {{ .Values.diskCache.persistence.existingClaim | default (include "scraperBot.cache.fullname" .) }}
            {{- end }}
