name: "Publish chart"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-chart:
    name: "Build chart"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set chart version
        run: |
          VERSION="${GITHUB_REF/refs\/tags\//}"
          VERSION="${VERSION/v/}"
          sed -i "s|^version:.*|version:\ \"${VERSION}\"|g" Chart.yaml
      - name: Helm tool installer
        uses: Azure/setup-helm@v4.2.0
        with:
          version: "3.15.3"
      - name: Build chart
        run: |
          helm dependency update
          helm package .
      - uses: actions/upload-artifact@v4
        with:
          name: charts
          path: "*.tgz"

  publish-chart:
    name: "Publish chart to owner repository"
    runs-on: ubuntu-latest
    needs: build-chart
    steps:
      - uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/charts'
          ref: 'charts'
          token: '${{ secrets.CHARTS_REPO_TOKEN }}'
      - uses: actions/download-artifact@v4
        with:
          name: charts
      - name: Push chart
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add *.tgz
          export CHART_FILENAMES="$(git --no-pager diff --name-only --cached -- '*.tgz' | tr '\n' ' ')"
          git commit -m "Add ${CHART_FILENAMES}"
          git push origin charts

  create-release:
    name: "Create release on GitHub"
    runs-on: ubuntu-latest
    needs: build-chart
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: charts
      - uses: softprops/action-gh-release@v2
        with:
          files: "*.tgz"
          generate_release_notes: true
          make_latest: true
